name: prepublish-storybook

on:
  pull_request:
    types:
      - closed
    paths:
      - 'src/**'

jobs:
  send_webhook:
    if: ${{ github.event.pull_request.merged }} == true
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: '머지된 pr의 제목 ${{ github.event.pull_request.title }}'
